# provider: anthropic
# model: claude-sonnet-4-20250514
# max_tokens: 32768

provider: deepseek
model: deepseek-chat
max_tokens: 8192

max_iterations: 5
confidence_threshold: 0.8

# Reviewer type: "default", "robust", or "structured"
# - default: Simple regex extraction (current)
# - robust: Multiple patterns + retry (recommended for quick improvement)
# - structured: JSON schema output (best practice for production)
reviewer_type: robust

data_dir: data
specs_dir: specs
logs_dir: logs

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

