name: Compare and Merge Specs

on:
  workflow_dispatch:
    inputs:
      source_file:
        description: 'Source file to merge from'
        required: true
        default: 'specs/fe_spec_final.md'
        type: choice
        options:
          - specs/fe_spec_final.md
          - specs/fe_spec_review.md
      target_file:
        description: 'Target file to merge into'
        required: true
        default: 'specs/fe_spec.md'
      auto_merge:
        description: 'Automatically merge without creating PR'
        required: false
        default: false
        type: boolean

jobs:
  compare-specs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Generate comparison report
      run: |
        python scripts/compare_specs.py \
          --source ${{ github.event.inputs.source_file }} \
          --target ${{ github.event.inputs.target_file }} \
          --output comparison_report.md
        
    - name: Upload comparison report
      uses: actions/upload-artifact@v4
      with:
        name: comparison-report
        path: comparison_report.md
        retention-days: 7
        
    - name: Display comparison summary
      run: |
        echo "## Comparison Report" >> $GITHUB_STEP_SUMMARY
        cat comparison_report.md >> $GITHUB_STEP_SUMMARY
        
    - name: Merge specs
      if: ${{ github.event.inputs.auto_merge == 'true' }}
      run: |
        cp ${{ github.event.inputs.source_file }} ${{ github.event.inputs.target_file }}
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add ${{ github.event.inputs.target_file }}
        git commit -m "chore: Auto-merge ${{ github.event.inputs.source_file }} into ${{ github.event.inputs.target_file }}"
        git push
        
    - name: Create merge PR
      if: ${{ github.event.inputs.auto_merge != 'true' }}
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: Merge reviewed spec changes'
        branch: merge/spec-review-${{ github.run_number }}
        delete-branch: true
        title: 'Merge: ${{ github.event.inputs.source_file }} → ${{ github.event.inputs.target_file }}'
        body: |
          ## Spec Merge Request
          
          This PR proposes merging changes from `${{ github.event.inputs.source_file }}` into `${{ github.event.inputs.target_file }}`.
          
          ### Changes:
          - Source: `${{ github.event.inputs.source_file }}`
          - Target: `${{ github.event.inputs.target_file }}`
          
          ### Comparison Report:
          See the attached artifact for the full comparison report.
          
          Please review the differences before merging.
        labels: |
          merge
          review-required

